#!/usr/bin/env bash
# Runtime tests for the generic error-response contract (nearai/infra#192).
#
# What this covers (complementing tests/test-headers.sh, which exercises
# backend-produced responses): errors generated by nginx ITSELF must return
# the minimal static JSON envelope with Content-Type application/json, the
# original status code, and no version/implementation disclosure in the body —
# while backend-produced error envelopes still pass through byte-for-byte and
# the 444/backend-down close-connection contract is preserved.
#
#   Plain listener (default.conf.template):
#     - malformed request line            -> 400 + generic 4xx JSON envelope
#     - oversized Content-Length (>100m)  -> 413 + generic 4xx JSON envelope
#     - 20k-char URI                      -> 414 + generic 4xx JSON envelope
#     - backend-produced 404 envelope     -> passes through byte-for-byte
#     - backend down                      -> connection closed, no HTTP error page
#   TLS listener (tls.conf.template):
#     - plain HTTP sent to the TLS port   -> 400 (497 remap) + generic 4xx JSON
#     - 20k-char URI over TLS             -> 414 + generic 4xx JSON envelope
#     - backend-produced 404 envelope     -> passes through byte-for-byte
#
# Runs against the image built from this repo's Dockerfile (the shipped
# artifact). VALIDATE_IMAGE=<ref> skips the build (same convention as
# validate-nginx-config.sh; the docker layer cache makes a repeat build in the
# same CI job nearly free).
#
# Requirements: docker, curl. Run from anywhere:
#   ./tests/test-error-responses.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

DOMAIN="ingress-test.invalid"
BACKEND_HOST="backend"
BACKEND_PORT="3000"

GENERIC_4XX='{"error":{"message":"The request could not be processed.","type":"invalid_request_error","param":null,"code":null}}'
BACKEND_404='{"error":{"message":"model not found","type":"invalid_request_error","param":null,"code":null}}'

IMAGE="${VALIDATE_IMAGE:-}"
if [[ -z "$IMAGE" ]]; then
    IMAGE="cvm-ingress-validate:local"
    echo "Building $IMAGE from $REPO_ROOT/Dockerfile"
    docker build -q -t "$IMAGE" "$REPO_ROOT" >/dev/null
fi
echo "Using image: $IMAGE"

WORK_DIR="$(mktemp -d)"
NET="generr-net-$$"
BACKEND_CTR="generr-backend-$$"
PLAIN_CTR="generr-plain-$$"
TLS_CTR="generr-tls-$$"
PLAIN_PORT="$((20000 + RANDOM % 10000))"
TLS_PORT="$((30000 + RANDOM % 10000))"

cleanup() {
    docker rm -f "$BACKEND_CTR" "$PLAIN_CTR" "$TLS_CTR" >/dev/null 2>&1 || true
    docker network rm "$NET" >/dev/null 2>&1 || true
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

fail() {
    echo "FAIL: $*" >&2
    exit 1
}

# --- Render templates exactly like entrypoint.sh generate_nginx_config -------

render() {
    local template="$1" out="$2"
    docker run --rm -i \
        -e DOLLAR='$' -e DOMAIN="$DOMAIN" -e BACKEND_HOST="$BACKEND_HOST" -e BACKEND_PORT="$BACKEND_PORT" \
        --entrypoint envsubst "$IMAGE" <"$template" >"$out"
}

render "$REPO_ROOT/nginx/default.conf.template" "$WORK_DIR/default.conf"
render "$REPO_ROOT/nginx/tls.conf.template" "$WORK_DIR/tls.conf"
echo "Rendered both templates"

mkdir -p "$WORK_DIR/certs/$DOMAIN"
docker run --rm --entrypoint sh -v "$WORK_DIR/certs:/certs" "$IMAGE" -c "
    openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -nodes -days 2 \
        -subj '/CN=$DOMAIN' \
        -keyout '/certs/$DOMAIN/privkey.pem' \
        -out '/certs/$DOMAIN/fullchain.pem' &&
    chmod -R a+r /certs
" >/dev/null 2>&1 || fail "could not generate test certificate"

# --- Containers ---------------------------------------------------------------

# Stub backend that answers with its own documented-style error envelope, to
# prove backend-produced errors are NOT rewritten by the ingress.
cat >"$WORK_DIR/backend.conf" <<EOF
server {
    listen 3000;
    default_type application/json;

    location = /ok      { return 200 '{"ok":true}'; }
    location = /missing { return 404 '$BACKEND_404'; }
}
EOF

docker network create "$NET" >/dev/null

docker run -d --name "$BACKEND_CTR" --network "$NET" --network-alias "$BACKEND_HOST" \
    -v "$WORK_DIR/backend.conf:/etc/nginx/conf.d/default.conf:ro" \
    --entrypoint sh "$IMAGE" -c 'mkdir -p /run/nginx && exec nginx -g "daemon off;"' >/dev/null

docker run -d --name "$PLAIN_CTR" --network "$NET" \
    -p "127.0.0.1:$PLAIN_PORT:8443" \
    -v "$REPO_ROOT/nginx/nginx.conf:/etc/nginx/nginx.conf:ro" \
    -v "$WORK_DIR/default.conf:/etc/nginx/conf.d/default.conf:ro" \
    --entrypoint sh "$IMAGE" -c 'mkdir -p /run/nginx && exec nginx -g "daemon off;"' >/dev/null

docker run -d --name "$TLS_CTR" --network "$NET" \
    -p "127.0.0.1:$TLS_PORT:8443" \
    -v "$REPO_ROOT/nginx/nginx.conf:/etc/nginx/nginx.conf:ro" \
    -v "$WORK_DIR/tls.conf:/etc/nginx/conf.d/default.conf:ro" \
    -v "$WORK_DIR/certs:/certs:ro" \
    --entrypoint sh "$IMAGE" -c 'mkdir -p /run/nginx && exec nginx -g "daemon off;"' >/dev/null

PLAIN="http://127.0.0.1:$PLAIN_PORT"
TLS="https://127.0.0.1:$TLS_PORT"
for i in $(seq 1 30); do
    if [[ "$(curl -s --max-time 2 "$PLAIN/nginx-health" || true)" == *ok* ]] &&
        [[ "$(curl -ks --max-time 2 "$TLS/nginx-health" || true)" == *ok* ]]; then
        break
    fi
    if [[ "$i" == "30" ]]; then
        docker logs "$PLAIN_CTR" >&2 || true
        docker logs "$TLS_CTR" >&2 || true
        fail "ingress containers did not become ready"
    fi
    sleep 1
done
echo "Ingress up: plain on :$PLAIN_PORT, TLS on :$TLS_PORT (backend stub on :$BACKEND_PORT)"

# --- Helpers ------------------------------------------------------------------

# assert_generic <label> <raw response with headers, CRs stripped> <want_status>
# Asserts: status, Content-Type application/json, body == the generic 4xx
# envelope, and no server-version/implementation disclosure in the body.
assert_generic() {
    local label="$1" raw="$2" want_status="$3"
    local status ct body
    read -r _ status _ <<<"$raw"
    [[ "$status" == "$want_status" ]] || fail "$label: expected status $want_status, got $status"

    ct="$(printf '%s' "$raw" | grep -ci '^content-type: application/json' || true)"
    [[ "$ct" == "1" ]] || fail "$label: expected Content-Type application/json, headers were: $(printf '%s' "$raw" | head -8)"

    body="$(printf '%s' "$raw" | tail -n1)"
    [[ "$body" == "$GENERIC_4XX" ]] || fail "$label: body is not the generic envelope: '$body'"

    case "$body" in
        *nginx*) fail "$label: body discloses server software: '$body'" ;;
    esac
    echo "PASS: $label -> $status, generic JSON envelope"
}

# raw_request <port> <payload> — send raw bytes over TCP, print the response
# with CRs stripped. Used where curl cannot produce the malformed input.
raw_request() {
    local port="$1" payload="$2"
    timeout 10 bash -c '
        exec 3<>"/dev/tcp/127.0.0.1/$0"
        printf "%b" "$1" >&3
        cat <&3
    ' "$port" "$payload" | tr -d '\r'
}

LONG_PATH="/$(printf 'a%.0s' $(seq 1 20000))"

# --- Plain listener: nginx-generated errors -----------------------------------

assert_generic "plain: malformed request line" \
    "$(raw_request "$PLAIN_PORT" 'GARBAGE\r\n\r\n')" 400

assert_generic "plain: oversized Content-Length (413)" \
    "$(raw_request "$PLAIN_PORT" "POST / HTTP/1.1\r\nHost: $DOMAIN\r\nContent-Length: 209715201\r\nConnection: close\r\n\r\n")" 413

assert_generic "plain: 20k-char URI (414)" \
    "$(curl -si --max-time 15 "$PLAIN$LONG_PATH" | tr -d '\r')" 414

# --- TLS listener: nginx-generated errors -------------------------------------

assert_generic "tls: plain HTTP to TLS port (497 remap)" \
    "$(curl -si --max-time 15 "http://127.0.0.1:$TLS_PORT/v1/models" | tr -d '\r')" 400

# Over HTTP/2 an oversized :path is rejected at the protocol layer (stream
# error, no HTTP response to assert on), so pin HTTP/1.1 to exercise the
# listener's error_page path.
assert_generic "tls: 20k-char URI (414, HTTP/1.1)" \
    "$(curl -ksi --http1.1 --max-time 15 "$TLS$LONG_PATH" | tr -d '\r')" 414

# --- Backend-produced errors still pass through byte-for-byte -----------------

for base_label in "plain|$PLAIN|" "tls|$TLS|-k"; do
    IFS='|' read -r label base kflag <<<"$base_label"
    raw="$(curl -si $kflag --max-time 15 "$base/missing" | tr -d '\r')"
    read -r _ status _ <<<"$raw"
    [[ "$status" == "404" ]] || fail "$label: backend 404 expected, got $status"
    body="$(printf '%s' "$raw" | tail -n1)"
    [[ "$body" == "$BACKEND_404" ]] || fail "$label: backend envelope was rewritten: '$body'"
    echo "PASS: $label: backend-produced 404 envelope passes through untouched"
done

# --- Backend down: 444 close-connection contract preserved --------------------

docker stop "$BACKEND_CTR" >/dev/null
sleep 6  # let the 5s resolver cache expire so the failure path is exercised

out_file="$WORK_DIR/backend-down.out"
set +e
curl -s --max-time 15 -o "$out_file" "$PLAIN/ok"
rc=$?
set -e
# 52 = empty reply, 56 = connection reset: both mean nginx closed the
# connection (return 444) instead of serving an HTTP error page.
[[ "$rc" == "52" || "$rc" == "56" ]] || fail "backend down: expected curl exit 52/56 (connection closed), got $rc"
[[ ! -s "$out_file" ]] || fail "backend down: expected empty response, got: $(cat "$out_file")"
echo "PASS: backend down -> connection closed (444 contract), no error page"

echo
echo "All error-response tests passed."
